### ISSUE TITLE
Insue with the reading of the audio file of the skin and the ffmpeg page is down

### ISSUE THREAD

**Issue by i-yitsure** [uyitroa/osr2mp4-app#75]
![image](https://user-images.githubusercontent.com/28587232/115287953-3cc0d900-a127-11eb-8470-05133d8e57de.png)
Some help for this?
And the page
![image](https://user-images.githubusercontent.com/28587232/115288298-ab9e3200-a127-11eb-8842-3d6fcf94a41a.png)

**Comment by uyitroa** [comment]
@i-yitsure  The first error is due to the skin. You can either use a different skin, or replace the normal-slidertick.ogg with something else (as it shows in the error).

For the second error,
https://ffmpeg.zeranoe.com/builds/ got closed down on Sep 18
you can download the libraries using wayback machine https://web.archive.org/web/20200916091820mp_/https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-4.3.1-win64-shared.zip

**Comment by i-yitsure** [comment]
Okay, long time ago i discovered the .wav files of same for compensate but thanks
Okay i will do that with respect to the libraries
Thanks so much
